tasks:
 - tox -e flake8
 - tox -e isort
 - tox -e py34-pillow
 - tox -e py34-django17
 - tox -e py34-django18
 - tox -e py34-redis
 - coverage combine && coverage report && coverage xml
 - tox -e docs

services:
 - redis-server

coverage:
  path: coverage.xml
  parser: python
