tasks:
 - tox -e py34-pillow
 - tox -e py34-django17
 - tox -e py34-django18
 - tox -e py34-redis
 - flake8
 - isort -rc -c thumbnails tests
 - coverage combine && coverage report && coverage xml
 - tox -e py34-docs

services:
 - redis-server

coverage:
  path: coverage.xml
  parser: python
