language: python

python:
  - "3.4"

cache:
  apt:
  directories:
    - .tox

services:
 - redis-server

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libjpeg62 libjpeg62-dev zlib1g-dev

install:
 - pip install -U pip wheel
 - pip install -q coveralls tox hide-env

script:
 - tox | hide-env GH_TOKEN PYPI_PASSWORD

after_success:
 - git config --global user.name "semantic-release"
 - git config --global user.email "semantic-release@travis"
 - pip install python-semantic-release
 - semantic-release publish | hide-env GH_TOKEN PYPI_PASSWORD



